FROM node:14

WORKDIR /app

RUN apt-get update && apt-get install -y build-essential

COPY package*.json ./

RUN npm install

COPY . .

CMD [ "npm", "start" ]
#! iniciar o dokcer --> systemctl start docker

#Docker. Em vez disso, o Docker recomenda o uso do "buildx" que é um componente do Docker que usa o BuildKit para construir imagens.

# Para resolver esse problema, você pode seguir as instruções do aviso e instalar o buildx. Isso pode ser feito seguindo os passos no link fornecido na mensagem de aviso. Uma vez que você tenha instalado o buildx, você pode usá-lo para construir suas imagens Docker com o comando "docker buildx build".