# Use uma imagem base
FROM ubuntu:20.04

# Definir variáveis de ambiente
ENV DEBIAN_FRONTEND noninteractive


# Define o diretório de trabalho para o main.js
WORKDIR /home/pedrov/Documentos/GitHub/Chatbot-Whatsapp/Chatbot - Delivary e Entregas/Chatbot Groundon Dev/Groundon 8 - AWS/src/Chatbot-JS


# Atualizando o servidor
RUN apt-get update && apt-get upgrade -y

# instala o NodeJs mais recente
RUN apt-get install -y curl
RUN curl -fsSL https://deb.nodesource.com/setup_19.x | bash -
RUN apt-get install -y nodejs 
RUN apt-get install -y libglib2.0-0



# Copia os arquivos necessários para dentro do container
#COPY path/to/libs /app/libs

# Copia o main.js para o diretório de trabalho
#COPY main.js .

# Copia o arquivo start.sh para o diretório de trabalho
COPY start-chatbot.sh .
RUN chmod +x start-chatbot.sh

#! instala o npm e tzdata

# Defina a porta na qual a aplicação será executada
EXPOSE 7000

# Defina o comando que será executado quando o container for iniciado
CMD "./start-chatbot.sh"