FROM node:16.18

WORKDIR /home/pedrov/Documentos/GitHub/Chatbot-Whatsapp/Chatbot - Delivary e Entregas/Chatbot Groundon Stable/src/Robo/

COPY package*.json ./

RUN npm install 

COPY . .

CMD node main.js



